server:
  port: 8282

eureka:
  instance:
    prefer-ip-address: true # Registers ip rather than server name
  client:
    register-with-eureka: true # register this app at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery service location

spring:
  application:
    name: Si-Exam-Gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #Enables eureka discovery service
      routes:
        - id: si-exam-loginsystem
          uri: lb://si-exam-loginSystem
          predicates:
            - Path=/users/**, /auth/**

